import React, { useState } from 'react';
import { useLanguage } from '@/contexts/LanguageContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { 
  Copy, Download, FileKey, Terminal, AlertTriangle, 
  CheckCircle2, Plus, X, Shield 
} from 'lucide-react';
import { toast } from 'sonner';

interface SAN {
  type: 'DNS' | 'IP';
  value: string;
}

const CsrGenerator: React.FC = () => {
  const { t } = useLanguage();
  
  // Form State
  const [cn, setCn] = useState('');
  const [sans, setSans] = useState<SAN[]>([]);
  const [organization, setOrganization] = useState('');
  const [organizationalUnit, setOrganizationalUnit] = useState('');
  const [country, setCountry] = useState('SA');
  const [state, setState] = useState('');
  const [locality, setLocality] = useState('');
  const [keySize, setKeySize] = useState('2048');
  
  // Generated outputs
  const [opensslCommand, setOpensslCommand] = useState('');
  const [opensslConfig, setOpensslConfig] = useState('');
  const [generatedKey, setGeneratedKey] = useState('');
  
  const addSan = () => {
    setSans([...sans, { type: 'DNS', value: '' }]);
  };
  
  const removeSan = (index: number) => {
    setSans(sans.filter((_, i) => i !== index));
  };
  
  const updateSan = (index: number, field: keyof SAN, value: string) => {
    const newSans = [...sans];
    newSans[index] = { ...newSans[index], [field]: value };
    setSans(newSans);
  };
  
  const generateOpensslConfig = () => {
    const validSans = sans.filter(san => san.value.trim());
    const sanEntries = validSans.map((san, i) => 
      `${san.type}.${i + 2} = ${san.value}`
    ).join('\n');
    
    const stLine = state ? `ST = ${state}` : '# ST = State';
    const lLine = locality ? `L = ${locality}` : '# L = Locality';
    const ouLine = organizationalUnit ? `OU = ${organizationalUnit}` : '# OU = Organizational Unit';
    
    return `# OpenSSL CSR Configuration
# Generated by IT Infrastructure Manager
# Date: ${new Date().toISOString().split('T')[0]}

[req]
default_bits = ${keySize}
default_keyfile = ${cn.replace(/[^a-zA-Z0-9]/g, '_')}.key
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no
encrypt_key = no

[req_distinguished_name]
C = ${country}
${stLine}
${lLine}
O = ${organization || 'Organization'}
${ouLine}
CN = ${cn}

[req_ext]
subjectAltName = @alt_names
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
basicConstraints = CA:FALSE

[alt_names]
DNS.1 = ${cn}
${sanEntries}
`;
  };
  
  const generateOpensslCommand = () => {
    const safeFileName = cn.replace(/[^a-zA-Z0-9]/g, '_');
    const keyFile = `${safeFileName}.key`;
    const csrFile = `${safeFileName}.csr`;
    const configFile = `${safeFileName}.cnf`;
    
    return `# ═══════════════════════════════════════════════════════════════
# CSR Generation Commands for: ${cn}
# ═══════════════════════════════════════════════════════════════

# Step 1: Save the configuration file as "${configFile}"
# (Download it using the button above)

# Step 2: Generate private key and CSR in one command
openssl req -new -newkey rsa:${keySize} -nodes \\
  -keyout ${keyFile} \\
  -out ${csrFile} \\
  -config ${configFile}

# Step 3: Set proper permissions on private key (Linux/Mac)
chmod 600 ${keyFile}

# Step 4: Verify the CSR is valid
openssl req -text -noout -verify -in ${csrFile}

# Step 5: View CSR content (optional)
openssl req -in ${csrFile} -text -noout

# ═══════════════════════════════════════════════════════════════
# Alternative: Generate key separately first
# ═══════════════════════════════════════════════════════════════

# Generate 4096-bit RSA key (more secure)
# openssl genrsa -out ${keyFile} 4096

# Then create CSR using existing key
# openssl req -new -key ${keyFile} -out ${csrFile} -config ${configFile}
`;
  };
  
  const handleGenerate = () => {
    if (!cn) {
      toast.error(t('itTools.csrCnRequired'));
      return;
    }
    
    setOpensslConfig(generateOpensslConfig());
    setOpensslCommand(generateOpensslCommand());
    toast.success(t('itTools.csrGenerated'));
  };
  
  // Client-side key generation using WebCrypto
  const generateClientSide = async () => {
    if (!cn) {
      toast.error(t('itTools.csrCnRequired'));
      return;
    }

    try {
      const keyPair = await crypto.subtle.generateKey(
        {
          name: 'RSASSA-PKCS1-v1_5',
          modulusLength: parseInt(keySize),
          publicExponent: new Uint8Array([1, 0, 1]),
          hash: 'SHA-256'
        },
        true,
        ['sign', 'verify']
      );
      
      // Export private key
      const privateKeyBuffer = await crypto.subtle.exportKey('pkcs8', keyPair.privateKey);
      const privateKeyBase64 = arrayBufferToBase64(privateKeyBuffer);
      setGeneratedKey(formatPem(privateKeyBase64, 'PRIVATE'));
      
      // Also generate config for CSR creation with OpenSSL
      setOpensslConfig(generateOpensslConfig());
      setOpensslCommand(generateOpensslCommand());
      
      toast.success(t('itTools.keyGenerated'));
      toast.info(t('itTools.csrNeedsOpenssl'));
    } catch (error) {
      console.error('Key generation error:', error);
      toast.error(t('common.error'));
    }
  };
  
  const copyToClipboard = async (text: string) => {
    await navigator.clipboard.writeText(text);
    toast.success(t('common.copied'));
  };
  
  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(t('itTools.fileDownloaded'));
  };
  
  return (
    <div className="space-y-6">
      <Tabs defaultValue="generate">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="generate" className="gap-2">
            <Terminal className="h-4 w-4" />
            {t('itTools.csrOpenssl')}
          </TabsTrigger>
          <TabsTrigger value="clientside" className="gap-2">
            <Shield className="h-4 w-4" />
            {t('itTools.csrClientSide')}
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="generate" className="space-y-4 mt-4">
          {/* Certificate Details Form */}
          <div className="grid gap-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>{t('itTools.csrCommonName')} *</Label>
                <Input 
                  placeholder="www.example.com" 
                  value={cn}
                  onChange={(e) => setCn(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>{t('itTools.csrKeySize')}</Label>
                <Select value={keySize} onValueChange={setKeySize}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="2048">2048 bits</SelectItem>
                    <SelectItem value="4096">4096 bits ({t('itTools.recommended')})</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
            
            {/* SANs */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label>{t('itTools.csrSans')}</Label>
                <Button type="button" size="sm" variant="outline" onClick={addSan}>
                  <Plus className="h-4 w-4 me-1" />
                  {t('common.add')}
                </Button>
              </div>
              <p className="text-xs text-muted-foreground">
                {t('itTools.csrSansHint')}
              </p>
              {sans.map((san, index) => (
                <div key={index} className="flex gap-2">
                  <Select 
                    value={san.type} 
                    onValueChange={(v) => updateSan(index, 'type', v as 'DNS' | 'IP')}
                  >
                    <SelectTrigger className="w-24">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="DNS">DNS</SelectItem>
                      <SelectItem value="IP">IP</SelectItem>
                    </SelectContent>
                  </Select>
                  <Input 
                    placeholder={san.type === 'DNS' ? 'mail.example.com' : '192.168.1.1'}
                    value={san.value}
                    onChange={(e) => updateSan(index, 'value', e.target.value)}
                    className="flex-1"
                  />
                  <Button 
                    type="button" 
                    size="icon" 
                    variant="ghost"
                    onClick={() => removeSan(index)}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
            
            {/* Organization Details */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>{t('itTools.csrOrganization')}</Label>
                <Input 
                  placeholder="My Company Ltd" 
                  value={organization}
                  onChange={(e) => setOrganization(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>{t('itTools.csrOu')}</Label>
                <Input 
                  placeholder="IT Department" 
                  value={organizationalUnit}
                  onChange={(e) => setOrganizationalUnit(e.target.value)}
                />
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label>{t('itTools.csrCountry')}</Label>
                <Input 
                  placeholder="SA" 
                  maxLength={2}
                  value={country}
                  onChange={(e) => setCountry(e.target.value.toUpperCase())}
                />
              </div>
              <div className="space-y-2">
                <Label>{t('itTools.csrState')}</Label>
                <Input 
                  placeholder="Riyadh Region" 
                  value={state}
                  onChange={(e) => setState(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>{t('itTools.csrLocality')}</Label>
                <Input 
                  placeholder="Riyadh" 
                  value={locality}
                  onChange={(e) => setLocality(e.target.value)}
                />
              </div>
            </div>
          </div>
          
          <Button onClick={handleGenerate} className="w-full gap-2">
            <FileKey className="h-4 w-4" />
            {t('itTools.csrGenerate')}
          </Button>
          
          {/* Generated Outputs */}
          {opensslConfig && (
            <div className="space-y-4">
              <Card>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-sm">{t('itTools.csrConfigFile')}</CardTitle>
                    <div className="flex gap-2">
                      <Button 
                        size="sm" 
                        variant="ghost"
                        onClick={() => copyToClipboard(opensslConfig)}
                      >
                        <Copy className="h-4 w-4" />
                      </Button>
                      <Button 
                        size="sm" 
                        variant="ghost"
                        onClick={() => downloadFile(opensslConfig, `${cn.replace(/[^a-zA-Z0-9]/g, '_')}.cnf`)}
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea 
                    value={opensslConfig} 
                    readOnly 
                    rows={12}
                    className="font-mono text-xs"
                  />
                </CardContent>
              </Card>
              
              <Card>
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-sm">{t('itTools.csrCommands')}</CardTitle>
                    <Button 
                      size="sm" 
                      variant="ghost"
                      onClick={() => copyToClipboard(opensslCommand)}
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea 
                    value={opensslCommand} 
                    readOnly 
                    rows={14}
                    className="font-mono text-xs"
                  />
                </CardContent>
              </Card>
            </div>
          )}
        </TabsContent>
        
        <TabsContent value="clientside" className="space-y-4 mt-4">
          <Alert>
            <Shield className="h-4 w-4" />
            <AlertTitle>{t('itTools.csrClientSideNote')}</AlertTitle>
            <AlertDescription>
              {t('itTools.csrClientSideDesc')}
            </AlertDescription>
          </Alert>

          {/* Same form fields for client-side */}
          <div className="grid gap-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>{t('itTools.csrCommonName')} *</Label>
                <Input 
                  placeholder="www.example.com" 
                  value={cn}
                  onChange={(e) => setCn(e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label>{t('itTools.csrKeySize')}</Label>
                <Select value={keySize} onValueChange={setKeySize}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="2048">2048 bits</SelectItem>
                    <SelectItem value="4096">4096 bits ({t('itTools.recommended')})</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>
          
          <Button onClick={generateClientSide} className="w-full gap-2">
            <Shield className="h-4 w-4" />
            {t('itTools.csrGenerateKey')}
          </Button>
          
          {generatedKey && (
            <>
              <Card className="border-destructive/50">
                <CardHeader className="pb-2">
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-sm flex items-center gap-2">
                      <AlertTriangle className="h-4 w-4 text-destructive" />
                      {t('itTools.privateKey')}
                    </CardTitle>
                    <div className="flex gap-2">
                      <Button 
                        size="sm" 
                        variant="ghost"
                        onClick={() => copyToClipboard(generatedKey)}
                      >
                        <Copy className="h-4 w-4" />
                      </Button>
                      <Button 
                        size="sm" 
                        variant="ghost"
                        onClick={() => downloadFile(generatedKey, `${cn.replace(/[^a-zA-Z0-9]/g, '_')}.key`)}
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <Textarea 
                    value={generatedKey} 
                    readOnly 
                    rows={8}
                    className="font-mono text-xs"
                  />
                  <p className="text-xs text-destructive mt-2 font-medium">
                    ⚠️ {t('itTools.privateKeyWarning')}
                  </p>
                </CardContent>
              </Card>

              {opensslConfig && (
                <Card>
                  <CardHeader className="pb-2">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-sm">{t('itTools.csrConfigFile')}</CardTitle>
                      <Button 
                        size="sm" 
                        variant="ghost"
                        onClick={() => downloadFile(opensslConfig, `${cn.replace(/[^a-zA-Z0-9]/g, '_')}.cnf`)}
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground mb-2">
                      {t('itTools.csrUseWithKey')}
                    </p>
                    <code className="text-xs bg-muted p-2 rounded block font-mono">
                      openssl req -new -key {cn.replace(/[^a-zA-Z0-9]/g, '_')}.key -out {cn.replace(/[^a-zA-Z0-9]/g, '_')}.csr -config {cn.replace(/[^a-zA-Z0-9]/g, '_')}.cnf
                    </code>
                  </CardContent>
                </Card>
              )}
            </>
          )}
        </TabsContent>
      </Tabs>
      
      {/* Best Practices */}
      <Card className="bg-muted/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-success" />
            {t('itTools.csrBestPractices')}
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">
          <ul className="list-disc list-inside space-y-1">
            <li>{t('itTools.csrTip1')}</li>
            <li>{t('itTools.csrTip2')}</li>
            <li>{t('itTools.csrTip3')}</li>
            <li>{t('itTools.csrTip4')}</li>
            <li>{t('itTools.csrTip5')}</li>
          </ul>
        </CardContent>
      </Card>
    </div>
  );
};

// Helper functions
const arrayBufferToBase64 = (buffer: ArrayBuffer): string => {
  const bytes = new Uint8Array(buffer);
  let binary = '';
  for (let i = 0; i < bytes.byteLength; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
};

const formatPem = (base64: string, type: string): string => {
  const lines = base64.match(/.{1,64}/g) || [];
  return `-----BEGIN ${type} KEY-----\n${lines.join('\n')}\n-----END ${type} KEY-----`;
};

export default CsrGenerator;
