import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.servers': 'السيرفرات',
    'nav.employees': 'الموظفين',
    'nav.employeePermissions': 'صلاحيات الموظفين',
    'nav.licenses': 'التراخيص',
    'nav.tasks': 'المهام',
    'nav.networks': 'النطاقات',
    'nav.domains': 'النطاقات',
    'nav.networkScan': 'فحص الشبكة',
    'nav.webApps': 'تطبيقات الويب',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'nav.vacations': 'الإجازات',
    'nav.employeeReports': 'تقارير الموظفين',
    'nav.auditLog': 'سجل العمليات',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم الرئيسية',
    'dashboard.totalServers': 'إجمالي السيرفرات',
    'dashboard.activeServers': 'السيرفرات النشطة',
    'dashboard.expiringLicenses': 'تراخيص قريبة الانتهاء',
    'dashboard.pendingTasks': 'المهام المعلقة',
    'dashboard.employees': 'الموظفين',
    'dashboard.networks': 'النطاقات',
    'dashboard.domains': 'النطاقات',
    'dashboard.selectNetwork': 'اختر النطاق',
    'dashboard.allNetworks': 'جميع النطاقات',
    'dashboard.allDomains': 'جميع النطاقات',
    'dashboard.myTasks': 'مهامي',
    'dashboard.teamTasks': 'مهام الفريق',
    'dashboard.allTasks': 'كل المهام',
    
    // Web Apps
    'webApps.title': 'تطبيقات الويب',
    'webApps.add': 'إضافة تطبيق',
    'webApps.manage': 'إدارة التطبيقات',
    'webApps.openLink': 'فتح الرابط',
    
    // Servers
    'servers.title': 'إدارة السيرفرات',
    'servers.add': 'إضافة سيرفر',
    'servers.import': 'استيراد من Excel',
    'servers.export': 'تصدير إلى Excel',
    'servers.name': 'اسم السيرفر',
    'servers.ip': 'عنوان IP',
    'servers.os': 'نظام التشغيل',
    'servers.osVersion': 'إصدار النظام',
    'servers.environment': 'البيئة',
    'servers.owner': 'المالك',
    'servers.responsible': 'المسؤول',
    'servers.description': 'الوصف',
    'servers.diskSpace': 'مساحة القرص',
    'servers.users': 'المستخدمين',
    'servers.network': 'الشبكة',
    'servers.domain': 'النطاق',
    'servers.status': 'الحالة',
    'servers.lastUpdate': 'آخر تحديث',
    'servers.notes': 'ملاحظات',
    
    // Environment types
    'env.production': 'إنتاج',
    'env.testing': 'اختبار',
    'env.development': 'تطوير',
    'env.staging': 'مرحلة ما قبل الإنتاج',
    
    // Status
    'status.active': 'نشط',
    'status.inactive': 'غير نشط',
    
    // Employees
    'employees.title': 'إدارة الموظفين',
    'employees.add': 'إضافة موظف',
    'employees.name': 'الاسم',
    'employees.position': 'المنصب',
    'employees.email': 'البريد الإلكتروني',
    'employees.phone': 'الهاتف',
    'employees.department': 'القسم',
    'employees.vacations': 'الإجازات',
    'employees.trainings': 'الدورات التدريبية',
    'employees.assignedServers': 'السيرفرات المسندة',
    'employees.addVacation': 'إضافة إجازة',
    'employees.addTraining': 'إضافة دورة',
    'employees.admin': 'مدير',
    'employees.employee': 'موظف',
    'employees.role': 'الدور',
    
    // Departments
    'dept.it': 'تكنولوجيا المعلومات',
    'dept.devops': 'DevOps',
    'dept.security': 'الأمن السيبراني',
    'dept.network': 'الشبكات',
    'dept.support': 'الدعم الفني',
    'dept.sysadmin': 'مدير النظام',
    
    // Vacations
    'vacations.title': 'إدارة الإجازات',
    'vacations.employee': 'الموظف',
    'vacations.type': 'نوع الإجازة',
    'vacations.annual': 'سنوية',
    'vacations.sick': 'مرضية',
    'vacations.emergency': 'طارئة',
    'vacations.unpaid': 'بدون راتب',
    'vacations.startDate': 'تاريخ البدء',
    'vacations.endDate': 'تاريخ النهاية',
    'vacations.status': 'الحالة',
    'vacations.pending': 'معلقة',
    'vacations.approved': 'مقبولة',
    'vacations.rejected': 'مرفوضة',
    'vacations.days': 'عدد الأيام',
    'vacations.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'vacations.selectEmployee': 'يرجى اختيار الموظف',
    'vacations.addSuccess': 'تم إضافة الإجازة بنجاح',
    
    // Employee Reports
    'employeeReports.title': 'تقارير الموظفين',
    'employeeReports.upload': 'رفع تقرير',
    'employeeReports.archive': 'أرشيف التقارير',
    'employeeReports.date': 'تاريخ التقرير',
    'employeeReports.uploadedBy': 'رفع بواسطة',
    'employeeReports.notes': 'ملاحظات',
    'employeeReports.file': 'الملف',
    'employeeReports.download': 'تحميل',
    
    // Licenses
    'licenses.title': 'إدارة التراخيص',
    'licenses.add': 'إضافة ترخيص',
    'licenses.name': 'اسم الترخيص',
    'licenses.product': 'المنتج',
    'licenses.key': 'مفتاح الترخيص',
    'licenses.startDate': 'تاريخ البدء',
    'licenses.expiryDate': 'تاريخ الانتهاء',
    'licenses.daysLeft': 'الأيام المتبقية',
    'licenses.server': 'السيرفر المرتبط',
    'licenses.domain': 'النطاق',
    'licenses.cost': 'التكلفة',
    'licenses.vendor': 'المورد',
    'licenses.notes': 'ملاحظات',
    'licenses.purchaseDate': 'تاريخ الشراء',
    'licenses.quantity': 'الكمية',
    'licenses.status': 'الحالة',
    
    // Tasks
    'tasks.pageTitle': 'إدارة المهام',
    'tasks.add': 'إضافة مهمة',
    'tasks.name': 'اسم المهمة',
    'tasks.title': 'العنوان',
    'tasks.description': 'الوصف',
    'tasks.assignee': 'المسؤول',
    'tasks.frequency': 'التكرار',
    'tasks.daily': 'يومية',
    'tasks.weekly': 'أسبوعية',
    'tasks.monthly': 'شهرية',
    'tasks.once': 'مرة واحدة',
    'tasks.dueDate': 'تاريخ الاستحقاق',
    'tasks.completed': 'مكتملة',
    'tasks.pending': 'معلقة',
    'tasks.overdue': 'متأخرة',
    'tasks.status': 'الحالة',
    'tasks.priority': 'الأولوية',
    
    // Networks
    'networks.name': 'اسم الشبكة',
    'networks.subnet': 'الشبكة الفرعية',
    'networks.gateway': 'البوابة',
    'networks.description': 'الوصف',
    
    // Reports
    'reports.exportFull': 'تصدير التقرير الكامل',
    'reports.infrastructureSummary': 'ملخص البنية التحتية',
    'reports.records': 'سجل',
    'reports.report': 'تقرير',
    'reports.serversByEnv': 'السيرفرات حسب البيئة',
    'reports.tasksStatus': 'حالة المهام',
    'reports.selectDomain': 'اختر النطاق',
    'reports.allDomains': 'جميع النطاقات',
    'reports.exportSuccess': 'تم تصدير التقرير بنجاح',
    'reports.fullExportSuccess': 'تم تصدير التقرير الكامل بنجاح',
    
    // Common
    'common.save': 'حفظ',
    'common.saving': 'جاري الحفظ...',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.search': 'بحث...',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.actions': 'الإجراءات',
    'common.noData': 'لا توجد بيانات',
    'common.loading': 'جاري التحميل...',
    'common.success': 'تم بنجاح',
    'common.error': 'حدث خطأ',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.days': 'يوم',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.offlineMode': 'وضع بدون اتصال',
    'common.export': 'تصدير',
    'common.import': 'استيراد',
    'common.refresh': 'تحديث',
    'common.signOut': 'تسجيل الخروج',
    'common.add': 'إضافة',
    'common.close': 'إغلاق',
    'common.required': 'مطلوب',
    'common.more': 'المزيد',
    'common.row': 'صف',
    'common.view': 'عرض',
    'common.permissions': 'صلاحيات',
    'common.resetPassword': 'إعادة تعيين كلمة المرور',

    // Permissions Page
    'permissions.title': 'إدارة الموظفين والصلاحيات',
    'permissions.subtitle': 'إضافة موظفين جدد وتعيين صلاحياتهم على الدومينات',
    'permissions.totalEmployees': 'إجمالي الموظفين',
    'permissions.admins': 'المسؤولون',
    'permissions.employees': 'الموظفون',
    'permissions.all': 'الكل',
    'permissions.searchEmployee': 'البحث عن موظف...',
    'permissions.employeeList': 'قائمة الموظفين',
    'permissions.employeeListDesc': 'عرض وإدارة جميع الموظفين المسجلين في النظام',
    'permissions.addEmployee': 'إضافة موظف',
    'permissions.ldapImport': 'استيراد من LDAP',
    'permissions.domains': 'الدومينات',
    'permissions.domainPermissions': 'صلاحيات الدومين',
    'permissions.canView': 'عرض',
    'permissions.canEdit': 'تعديل',
    'permissions.savePermissions': 'حفظ الصلاحيات',
    'permissions.deleteEmployee': 'حذف الموظف',
    'permissions.deleteConfirm': 'هل أنت متأكد من حذف هذا الموظف؟',
    'permissions.deleteWarning': 'سيتم حذف جميع بيانات الموظف نهائياً',
    'permissions.passwordResetSent': 'تم إرسال رابط إعادة تعيين كلمة المرور',
    'permissions.permissionsSaved': 'تم حفظ الصلاحيات بنجاح',
    'permissions.noAccess': 'ليس لديك صلاحية للوصول لهذه الصفحة',
    'permissions.employeeInfo': 'معلومات الموظف',
    'permissions.resetPasswordDesc': 'سيتم إرسال رابط إعادة تعيين كلمة المرور إلى البريد الإلكتروني',
    'permissions.noDomains': 'لا يوجد دومينات. قم بإضافة دومين أولاً من صفحة الشبكات.',
    'permissions.noEmployees': 'لا يوجد موظفين',
    'permissions.addNewEmployee': 'إضافة موظف جديد',
    'permissions.addEmployeeDesc': 'أدخل بيانات الموظف الجديد. سيتم إرسال رابط تأكيد البريد الإلكتروني.',
    'permissions.domain': 'الدومين',
    'permissions.notAssigned': 'لا يوجد',
    'permissions.notSpecified': 'لم يحدد',
    'permissions.permissionsFor': 'صلاحيات الموظف',
    'permissions.permissionsDesc': 'حدد الدومينات التي يمكن للموظف الوصول إليها. صلاحية "التعديل" تتيح له إضافة وتعديل السيرفرات والمهام.',
    'permissions.adding': 'جاري الإضافة...',
    'permissions.addEmployeeBtn': 'إضافة الموظف',

    // Form Labels
    'form.email': 'البريد الإلكتروني',
    'form.password': 'كلمة المرور',
    'form.fullName': 'الاسم الكامل',
    'form.department': 'القسم',
    'form.position': 'المنصب',
    'form.phone': 'رقم الهاتف',
    'form.role': 'الدور',
    'form.newPassword': 'كلمة المرور الجديدة',
    'form.minChars': 'أحرف على الأقل',
    'form.example': 'مثال',

    // Validation
    'validation.fillRequired': 'يرجى ملء جميع الحقول المطلوبة',
    'validation.passwordMin': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'validation.phoneFormat': 'رقم الهاتف يجب أن يبدأ بـ 05 ويتكون من 10 أرقام',

    // Sidebar Order
    'sidebar.orderTitle': 'ترتيب القائمة الجانبية',
    'sidebar.orderDesc': 'قم بترتيب عناصر القائمة الجانبية حسب تفضيلاتك',
    'sidebar.saveOrder': 'حفظ الترتيب',
    'sidebar.reset': 'إعادة تعيين',

    // Settings
    'settings.general': 'عام',
    'settings.mail': 'البريد',
    'settings.ldap': 'LDAP',
    'settings.ntp': 'NTP',
    'settings.templates': 'القوالب',
    'settings.appearance': 'المظهر',
    'settings.darkMode': 'الوضع الداكن',
    'settings.lightMode': 'الوضع الفاتح',
    'settings.appNameAr': 'اسم التطبيق (عربي)',
    'settings.appNameEn': 'اسم التطبيق (English)',
    'settings.customization': 'التخصيص',
    'settings.sectionOrder': 'ترتيب الأقسام',

    // Audit Log
    'auditLog.title': 'سجل العمليات',
    'auditLog.pageTitle': 'سجل التغييرات',
    'auditLog.subtitle': 'تتبع جميع العمليات والتغييرات في النظام',
    'auditLog.totalRecords': 'إجمالي السجلات',
    'auditLog.created': 'إنشاء',
    'auditLog.updated': 'تحديث',
    'auditLog.deleted': 'حذف',
    'auditLog.login': 'تسجيل دخول',
    'auditLog.logout': 'تسجيل خروج',
    'auditLog.searchPlaceholder': 'بحث في السجلات...',
    'auditLog.allActions': 'جميع العمليات',
    'auditLog.allTables': 'جميع الجداول',
    'auditLog.dateTime': 'التاريخ والوقت',
    'auditLog.user': 'المستخدم',
    'auditLog.action': 'العملية',
    'auditLog.table': 'الجدول',
    'auditLog.details': 'التفاصيل',
    'auditLog.noRecords': 'لا توجد سجلات',
    'auditLog.unknownUser': 'مستخدم غير معروف',
    'auditLog.create': 'إنشاء',
    'auditLog.update': 'تحديث',
    'auditLog.delete': 'حذف',

    // Table Names
    'table.servers': 'السيرفرات',
    'table.networks': 'الشبكات',
    'table.domains': 'الدومينات',
    'table.licenses': 'التراخيص',
    'table.tasks': 'المهام',
    'table.profiles': 'الموظفين',
    'table.vacations': 'الإجازات',
    'table.domain_memberships': 'صلاحيات الدومين',
    'table.website_applications': 'تطبيقات الويب',

    // Employee Reports Additional
    'employeeReports.reportType': 'نوع التقرير',
    'employeeReports.daily': 'يومي',
    'employeeReports.weekly': 'أسبوعي',
    'employeeReports.monthly': 'شهري',
    'employeeReports.preview': 'معاينة (أول 5 صفوف)',
    'employeeReports.readError': 'فشل في قراءة ملف Excel',
    'employeeReports.selectRequired': 'يرجى اختيار الموظف والملف',
    'employeeReports.uploadSuccess': 'تم رفع التقرير بنجاح',
    'employeeReports.deleteConfirm': 'هل أنت متأكد من حذف هذا التقرير؟',
    'employeeReports.deleteSuccess': 'تم حذف التقرير',
    'employeeReports.report': 'تقرير',

    // Web Apps Additional
    'webApps.subtitle': 'إدارة روابط تطبيقات الويب',
    'webApps.totalApps': 'إجمالي التطبيقات',
    'webApps.active': 'نشط',
    'webApps.disabled': 'معطل',
    'webApps.searchPlaceholder': 'البحث عن تطبيق...',
    'webApps.app': 'التطبيق',
    'webApps.url': 'الرابط',
    'webApps.category': 'التصنيف',
    'webApps.domain': 'النطاق',
    'webApps.status': 'الحالة',
    'webApps.public': 'عام',
    'webApps.publicForAll': 'عام للجميع',
    'webApps.noApps': 'لا توجد تطبيقات',
    'webApps.updateSuccess': 'تم تحديث التطبيق',
    'webApps.addSuccess': 'تم إضافة التطبيق',
    'webApps.deleteSuccess': 'تم حذف التطبيق',
    'webApps.saveFailed': 'فشل في حفظ التطبيق',
    'webApps.deleteFailed': 'فشل في حذف التطبيق',
    'webApps.editApp': 'تعديل التطبيق',
    'webApps.addApp': 'إضافة تطبيق',
    'webApps.appDesc': 'أضف رابط لتطبيق ويب للوصول السريع من لوحة التحكم',
    'webApps.appName': 'اسم التطبيق',
    'webApps.icon': 'الأيقونة',
    'webApps.description': 'الوصف',
    'webApps.selectCategory': 'اختر التصنيف',
    'webApps.enabled': 'مفعّل',
    'webApps.enabledDesc': 'إظهار التطبيق في لوحة التحكم',
    'webApps.saveChanges': 'حفظ التعديلات',
    'webApps.deleteConfirm': 'هل أنت متأكد؟',
    'webApps.deleteWarning': 'سيتم حذف التطبيق نهائياً. لا يمكن التراجع عن هذا الإجراء.',

    // Categories
    'category.infrastructure': 'البنية التحتية',
    'category.security': 'الأمان',
    'category.monitoring': 'المراقبة',
    'category.communication': 'التواصل',
    'category.development': 'التطوير',
    'category.other': 'أخرى',

    // Networks Additional
    'networks.domainsTab': 'الدومينات',
    'networks.networksTab': 'الشبكات',
    'networks.addDomain': 'إضافة دومين',
    'networks.addNetwork': 'إضافة شبكة',
    'networks.domainRequired': 'اسم الدومين مطلوب',
    'networks.domainUpdated': 'تم تحديث الدومين',
    'networks.domainAdded': 'تم إضافة الدومين',
    'networks.networkRequired': 'اسم الشبكة والدومين مطلوبين',
    'networks.networkUpdated': 'تم تحديث الشبكة',
    'networks.networkAdded': 'تم إضافة الشبكة',
    'networks.domainDeleted': 'تم حذف الدومين',
    'networks.networkDeleted': 'تم حذف الشبكة',
    'networks.addNewDomain': 'إضافة دومين جديد',
    'networks.addNewNetwork': 'إضافة شبكة جديدة',
    'networks.domainName': 'اسم الدومين',
    'networks.networkName': 'اسم الشبكة',
    'networks.domain': 'الدومين',
    'networks.selectDomain': 'اختر الدومين',
    'networks.dnsServers': 'خوادم DNS (مفصولة بفواصل)',
    'networks.networksCount': 'شبكات',
    'networks.serversCount': 'سيرفر',
    'networks.addDomainFirst': 'قم بإضافة دومين للبدء',
    'networks.addDomainThenNetwork': 'قم بإضافة دومين أولاً ثم أضف شبكات',
    'networks.addNetworkToStart': 'قم بإضافة شبكة للبدء',

    // Common additions
    'common.descriptionLabel': 'الوصف',
    'common.notSpecified': 'غير محدد',
    'common.example': 'مثال',

    // Auth
    'auth.rememberMe': 'تذكرني',
    'auth.sessionExpired': 'انتهت الجلسة',
    'auth.pleaseLoginAgain': 'يرجى تسجيل الدخول مجدداً',
    'auth.login': 'تسجيل الدخول',
    'auth.loggingIn': 'جارٍ تسجيل الدخول...',
    'auth.loginSuccess': 'تم تسجيل الدخول بنجاح',
    'auth.invalidCredentials': 'بيانات تسجيل الدخول غير صحيحة',

    // Server Enhancements
    'servers.beneficiary': 'المستفيد/القسم',
    'servers.primaryApp': 'التطبيق الأساسي',
    'servers.businessOwner': 'مالك الخدمة',
    'servers.veeamBackup': 'نسخ Veeam',
    'servers.isBackedUp': 'يأخذ نسخة؟',
    'servers.backupFrequency': 'تكرار النسخ',
    'servers.backupJobName': 'اسم Job',
    'servers.lastBackupStatus': 'آخر حالة',
    'servers.lastBackupDate': 'تاريخ آخر نسخة',
    'servers.backupNone': 'لا يوجد',
    'servers.backupDaily': 'يومي',
    'servers.backupWeekly': 'أسبوعي',
    'servers.filterByBackup': 'فلتر النسخ',
    'servers.filterByDepartment': 'فلتر القسم',
    'servers.backedUp': 'له نسخة',
    'servers.notBackedUp': 'بدون نسخة',

    // Network Scan
    'scan.title': 'فحص الشبكة',
    'scan.startScan': 'بدء الفحص',
    'scan.scanName': 'اسم الفحص',
    'scan.ipRange': 'نطاق IP',
    'scan.scanMode': 'وضع الفحص',
    'scan.basic': 'أساسي',
    'scan.credentialed': 'مع بيانات دخول',
    'scan.results': 'النتائج',
    'scan.importSelected': 'استيراد المحدد',
    'scan.discovered': 'تم اكتشاف',
    'scan.devices': 'أجهزة',
    'scan.running': 'جاري الفحص',
    'scan.completed': 'مكتمل',
    'scan.failed': 'فشل',
    'scan.pending': 'في الانتظار',
    'scan.selectForImport': 'اختر للاستيراد',
    'scan.hostname': 'اسم الجهاز',
    'scan.deviceType': 'نوع الجهاز',
    'scan.openPorts': 'المنافذ المفتوحة',
    'scan.server': 'سيرفر',
    'scan.workstation': 'محطة عمل',
    'scan.networkDevice': 'جهاز شبكة',
    'scan.printer': 'طابعة',
    'scan.unknown': 'غير معروف',
    'scan.history': 'سجل الفحوصات',

    // Task System Pro
    'tasks.myTasks': 'مهامي',
    'tasks.teamTasks': 'مهام الفريق',
    'tasks.kanban': 'لوحة Kanban',
    'tasks.calendar': 'التقويم',
    'tasks.templates': 'القوالب',
    'tasks.sla': 'مستوى الخدمة',
    'tasks.checklist': 'قائمة التحقق',
    'tasks.comments': 'التعليقات',
    'tasks.attachments': 'المرفقات',
    'tasks.evidence': 'الأدلة',
    'tasks.draft': 'مسودة',
    'tasks.assigned': 'تم الإسناد',
    'tasks.inProgress': 'قيد التنفيذ',
    'tasks.blocked': 'متوقفة',
    'tasks.inReview': 'في المراجعة',
    'tasks.done': 'مكتملة',
    'tasks.closed': 'مغلقة',
    'tasks.cancelled': 'ملغاة',
    'tasks.requester': 'الطالب',
    'tasks.reviewer': 'المراجع',
    'tasks.watchers': 'المتابعون',
    'tasks.linkedAssets': 'الأصول المرتبطة',
    'tasks.subtasks': 'المهام الفرعية',
    'tasks.addComment': 'إضافة تعليق',
    'tasks.addEvidence': 'إضافة دليل',
    'tasks.slaBreach': 'تجاوز SLA',
    'tasks.responseTime': 'وقت الاستجابة',
    'tasks.resolveTime': 'وقت الحل',
    'tasks.overdueTasks': 'المهام المتأخرة',
    'tasks.todayTasks': 'مهام اليوم',
    'tasks.upcomingTasks': 'المهام القادمة',

    // Priorities
    'priority.p1': 'حرجة',
    'priority.p2': 'عالية',
    'priority.p3': 'متوسطة',
    'priority.p4': 'منخفضة',
    
    // Additional Task Views
    'tasks.listView': 'قائمة',
    'tasks.kanbanView': 'Kanban',
    'tasks.calendarView': 'تقويم',
    'tasks.viewModes': 'طرق العرض',
    'tasks.createFromTemplate': 'إنشاء من قالب',
    'tasks.manageTemplates': 'إدارة القوالب',
    'tasks.noTemplates': 'لا يوجد قوالب',
    
    // Import/Export
    'import.review': 'مراجعة الاستيراد',
    'import.newRecords': 'سجلات جديدة',
    'import.toUpdate': 'للتحديث',
    'import.errors': 'أخطاء',
    'import.confirmImport': 'تأكيد الاستيراد',
    'import.dryRun': 'معاينة فقط',
    'import.downloadTemplate': 'تحميل القالب',
    
    'export.pdf': 'تصدير PDF',
    'export.excel': 'تصدير Excel',
    'export.fullReport': 'التقرير الكامل',
    'export.filtered': 'البيانات المفلترة',
    'export.summary': 'ملخص تنفيذي',
    
    // Reports Networks
    'reports.networks': 'الشبكات',
    
    // Server Filters
    'servers.selectDomain': 'اختر النطاق',
    'servers.selectNetwork': 'اختر الشبكة',
    'servers.filterByDomain': 'الفلترة حسب النطاق',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.servers': 'Servers',
    'nav.employees': 'Employees',
    'nav.employeePermissions': 'Employee Permissions',
    'nav.licenses': 'Licenses',
    'nav.tasks': 'Tasks',
    'nav.networks': 'Domains',
    'nav.domains': 'Domains',
    'nav.networkScan': 'Network Scan',
    'nav.webApps': 'Web Apps',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.vacations': 'Vacations',
    'nav.employeeReports': 'Employee Reports',
    'nav.auditLog': 'Audit Log',
    
    // Dashboard
    'dashboard.title': 'Main Dashboard',
    'dashboard.totalServers': 'Total Servers',
    'dashboard.activeServers': 'Active Servers',
    'dashboard.expiringLicenses': 'Expiring Licenses',
    'dashboard.pendingTasks': 'Pending Tasks',
    'dashboard.employees': 'Employees',
    'dashboard.networks': 'Domains',
    'dashboard.domains': 'Domains',
    'dashboard.selectNetwork': 'Select Domain',
    'dashboard.allNetworks': 'All Domains',
    'dashboard.allDomains': 'All Domains',
    'dashboard.myTasks': 'My Tasks',
    'dashboard.teamTasks': 'Team Tasks',
    'dashboard.allTasks': 'All Tasks',
    
    // Web Apps
    'webApps.title': 'Web Applications',
    'webApps.add': 'Add Application',
    'webApps.manage': 'Manage Apps',
    'webApps.openLink': 'Open Link',
    
    // Servers
    'servers.title': 'Server Management',
    'servers.add': 'Add Server',
    'servers.import': 'Import from Excel',
    'servers.export': 'Export to Excel',
    'servers.name': 'Server Name',
    'servers.ip': 'IP Address',
    'servers.os': 'Operating System',
    'servers.osVersion': 'OS Version',
    'servers.environment': 'Environment',
    'servers.owner': 'Owner',
    'servers.responsible': 'Responsible',
    'servers.description': 'Description',
    'servers.diskSpace': 'Disk Space',
    'servers.users': 'Users',
    'servers.network': 'Network',
    'servers.domain': 'Domain',
    'servers.status': 'Status',
    'servers.lastUpdate': 'Last Update',
    'servers.notes': 'Notes',
    
    // Environment types
    'env.production': 'Production',
    'env.testing': 'Testing',
    'env.development': 'Development',
    'env.staging': 'Staging',
    
    // Status
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    
    // Employees
    'employees.title': 'Employee Management',
    'employees.add': 'Add Employee',
    'employees.name': 'Name',
    'employees.position': 'Position',
    'employees.email': 'Email',
    'employees.phone': 'Phone',
    'employees.department': 'Department',
    'employees.vacations': 'Vacations',
    'employees.trainings': 'Training Courses',
    'employees.assignedServers': 'Assigned Servers',
    'employees.addVacation': 'Add Vacation',
    'employees.addTraining': 'Add Training',
    'employees.admin': 'Admin',
    'employees.employee': 'Employee',
    'employees.role': 'Role',
    
    // Departments
    'dept.it': 'IT',
    'dept.devops': 'DevOps',
    'dept.security': 'Security',
    'dept.network': 'Network',
    'dept.support': 'Support',
    'dept.sysadmin': 'System Admin',
    
    // Vacations
    'vacations.title': 'Vacation Management',
    'vacations.employee': 'Employee',
    'vacations.type': 'Vacation Type',
    'vacations.annual': 'Annual',
    'vacations.sick': 'Sick',
    'vacations.emergency': 'Emergency',
    'vacations.unpaid': 'Unpaid',
    'vacations.startDate': 'Start Date',
    'vacations.endDate': 'End Date',
    'vacations.status': 'Status',
    'vacations.pending': 'Pending',
    'vacations.approved': 'Approved',
    'vacations.rejected': 'Rejected',
    'vacations.days': 'Days',
    'vacations.fillRequired': 'Please fill all required fields',
    'vacations.selectEmployee': 'Please select an employee',
    'vacations.addSuccess': 'Vacation added successfully',
    
    // Employee Reports
    'employeeReports.title': 'Employee Reports',
    'employeeReports.upload': 'Upload Report',
    'employeeReports.archive': 'Reports Archive',
    'employeeReports.date': 'Report Date',
    'employeeReports.uploadedBy': 'Uploaded By',
    'employeeReports.notes': 'Notes',
    'employeeReports.file': 'File',
    'employeeReports.download': 'Download',
    
    // Licenses
    'licenses.title': 'License Management',
    'licenses.add': 'Add License',
    'licenses.name': 'License Name',
    'licenses.product': 'Product',
    'licenses.key': 'License Key',
    'licenses.startDate': 'Start Date',
    'licenses.expiryDate': 'Expiry Date',
    'licenses.daysLeft': 'Days Left',
    'licenses.server': 'Linked Server',
    'licenses.domain': 'Domain',
    'licenses.cost': 'Cost',
    'licenses.vendor': 'Vendor',
    'licenses.notes': 'Notes',
    'licenses.purchaseDate': 'Purchase Date',
    'licenses.quantity': 'Quantity',
    'licenses.status': 'Status',
    
    // Tasks
    'tasks.pageTitle': 'Task Management',
    'tasks.add': 'Add Task',
    'tasks.name': 'Task Name',
    'tasks.title': 'Title',
    'tasks.description': 'Description',
    'tasks.assignee': 'Assignee',
    'tasks.frequency': 'Frequency',
    'tasks.daily': 'Daily',
    'tasks.weekly': 'Weekly',
    'tasks.monthly': 'Monthly',
    'tasks.once': 'Once',
    'tasks.dueDate': 'Due Date',
    'tasks.completed': 'Completed',
    'tasks.pending': 'Pending',
    'tasks.overdue': 'Overdue',
    'tasks.status': 'Status',
    'tasks.priority': 'Priority',
    
    // Networks
    'networks.name': 'Network Name',
    'networks.subnet': 'Subnet',
    'networks.gateway': 'Gateway',
    'networks.description': 'Description',
    
    // Reports
    'reports.exportFull': 'Export Full Report',
    'reports.infrastructureSummary': 'Infrastructure Summary',
    'reports.records': 'records',
    'reports.report': 'Report',
    'reports.serversByEnv': 'Servers by Environment',
    'reports.tasksStatus': 'Tasks Status',
    'reports.selectDomain': 'Select Domain',
    'reports.allDomains': 'All Domains',
    'reports.exportSuccess': 'Report exported successfully',
    'reports.fullExportSuccess': 'Full report exported successfully',
    
    // Common
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.actions': 'Actions',
    'common.noData': 'No data available',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error occurred',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.days': 'days',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.offlineMode': 'Offline Mode',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.signOut': 'Sign Out',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.required': 'Required',
    'common.more': 'more',
    'common.row': 'Row',
    'common.view': 'View',
    'common.permissions': 'Permissions',
    'common.resetPassword': 'Reset Password',

    // Permissions Page
    'permissions.title': 'Employee & Permissions Management',
    'permissions.subtitle': 'Add new employees and assign domain permissions',
    'permissions.totalEmployees': 'Total Employees',
    'permissions.admins': 'Admins',
    'permissions.employees': 'Employees',
    'permissions.all': 'All',
    'permissions.searchEmployee': 'Search employee...',
    'permissions.employeeList': 'Employee List',
    'permissions.employeeListDesc': 'View and manage all registered employees',
    'permissions.addEmployee': 'Add Employee',
    'permissions.ldapImport': 'Import from LDAP',
    'permissions.domains': 'Domains',
    'permissions.domainPermissions': 'Domain Permissions',
    'permissions.canView': 'View',
    'permissions.canEdit': 'Edit',
    'permissions.savePermissions': 'Save Permissions',
    'permissions.deleteEmployee': 'Delete Employee',
    'permissions.deleteConfirm': 'Are you sure you want to delete this employee?',
    'permissions.deleteWarning': 'All employee data will be permanently deleted',
    'permissions.passwordResetSent': 'Password reset link has been sent',
    'permissions.permissionsSaved': 'Permissions saved successfully',
    'permissions.noAccess': 'You do not have access to this page',
    'permissions.employeeInfo': 'Employee Info',
    'permissions.resetPasswordDesc': 'Password reset link will be sent to the employee email',
    'permissions.noDomains': 'No domains available. Add a domain first from the Networks page.',
    'permissions.noEmployees': 'No employees found',
    'permissions.addNewEmployee': 'Add New Employee',
    'permissions.addEmployeeDesc': 'Enter new employee details. A confirmation email will be sent.',
    'permissions.domain': 'Domain',
    'permissions.notAssigned': 'None',
    'permissions.notSpecified': 'Not specified',
    'permissions.permissionsFor': 'Employee Permissions',
    'permissions.permissionsDesc': 'Select domains the employee can access. "Edit" permission allows adding and modifying servers and tasks.',
    'permissions.adding': 'Adding...',
    'permissions.addEmployeeBtn': 'Add Employee',

    // Form Labels
    'form.email': 'Email',
    'form.password': 'Password',
    'form.fullName': 'Full Name',
    'form.department': 'Department',
    'form.position': 'Position',
    'form.phone': 'Phone Number',
    'form.role': 'Role',
    'form.newPassword': 'New Password',
    'form.minChars': 'characters minimum',
    'form.example': 'Example',

    // Validation
    'validation.fillRequired': 'Please fill all required fields',
    'validation.passwordMin': 'Password must be at least 6 characters',
    'validation.phoneFormat': 'Phone must start with 05 and be 10 digits',

    // Sidebar Order
    'sidebar.orderTitle': 'Sidebar Menu Order',
    'sidebar.orderDesc': 'Arrange sidebar menu items according to your preferences',
    'sidebar.saveOrder': 'Save Order',
    'sidebar.reset': 'Reset',

    // Settings
    'settings.general': 'General',
    'settings.mail': 'Mail',
    'settings.ldap': 'LDAP',
    'settings.ntp': 'NTP',
    'settings.templates': 'Templates',
    'settings.appearance': 'Appearance',
    'settings.darkMode': 'Dark Mode',
    'settings.lightMode': 'Light Mode',
    'settings.appNameAr': 'App Name (Arabic)',
    'settings.appNameEn': 'App Name (English)',
    'settings.customization': 'Customization',
    'settings.sectionOrder': 'Section Order',

    // Audit Log
    'auditLog.title': 'Audit Log',
    'auditLog.pageTitle': 'Change Log',
    'auditLog.subtitle': 'Track all operations and changes in the system',
    'auditLog.totalRecords': 'Total Records',
    'auditLog.created': 'Created',
    'auditLog.updated': 'Updated',
    'auditLog.deleted': 'Deleted',
    'auditLog.login': 'Login',
    'auditLog.logout': 'Logout',
    'auditLog.searchPlaceholder': 'Search logs...',
    'auditLog.allActions': 'All Actions',
    'auditLog.allTables': 'All Tables',
    'auditLog.dateTime': 'Date & Time',
    'auditLog.user': 'User',
    'auditLog.action': 'Action',
    'auditLog.table': 'Table',
    'auditLog.details': 'Details',
    'auditLog.noRecords': 'No records found',
    'auditLog.unknownUser': 'Unknown User',
    'auditLog.create': 'Create',
    'auditLog.update': 'Update',
    'auditLog.delete': 'Delete',

    // Table Names
    'table.servers': 'Servers',
    'table.networks': 'Networks',
    'table.domains': 'Domains',
    'table.licenses': 'Licenses',
    'table.tasks': 'Tasks',
    'table.profiles': 'Employees',
    'table.vacations': 'Vacations',
    'table.domain_memberships': 'Domain Permissions',
    'table.website_applications': 'Web Applications',

    // Employee Reports Additional
    'employeeReports.reportType': 'Report Type',
    'employeeReports.daily': 'Daily',
    'employeeReports.weekly': 'Weekly',
    'employeeReports.monthly': 'Monthly',
    'employeeReports.preview': 'Preview (first 5 rows)',
    'employeeReports.readError': 'Failed to read Excel file',
    'employeeReports.selectRequired': 'Please select employee and file',
    'employeeReports.uploadSuccess': 'Report uploaded successfully',
    'employeeReports.deleteConfirm': 'Are you sure you want to delete this report?',
    'employeeReports.deleteSuccess': 'Report deleted',
    'employeeReports.report': 'Report',

    // Web Apps Additional
    'webApps.subtitle': 'Manage web application links',
    'webApps.totalApps': 'Total Applications',
    'webApps.active': 'Active',
    'webApps.disabled': 'Disabled',
    'webApps.searchPlaceholder': 'Search application...',
    'webApps.app': 'Application',
    'webApps.url': 'URL',
    'webApps.category': 'Category',
    'webApps.domain': 'Domain',
    'webApps.status': 'Status',
    'webApps.public': 'Public',
    'webApps.publicForAll': 'Public for all',
    'webApps.noApps': 'No applications found',
    'webApps.updateSuccess': 'Application updated',
    'webApps.addSuccess': 'Application added',
    'webApps.deleteSuccess': 'Application deleted',
    'webApps.saveFailed': 'Failed to save application',
    'webApps.deleteFailed': 'Failed to delete application',
    'webApps.editApp': 'Edit Application',
    'webApps.addApp': 'Add Application',
    'webApps.appDesc': 'Add a web app link for quick access from the dashboard',
    'webApps.appName': 'Application Name',
    'webApps.icon': 'Icon',
    'webApps.description': 'Description',
    'webApps.selectCategory': 'Select Category',
    'webApps.enabled': 'Enabled',
    'webApps.enabledDesc': 'Show application in dashboard',
    'webApps.saveChanges': 'Save Changes',
    'webApps.deleteConfirm': 'Are you sure?',
    'webApps.deleteWarning': 'The application will be permanently deleted. This action cannot be undone.',

    // Categories
    'category.infrastructure': 'Infrastructure',
    'category.security': 'Security',
    'category.monitoring': 'Monitoring',
    'category.communication': 'Communication',
    'category.development': 'Development',
    'category.other': 'Other',

    // Networks Additional
    'networks.domainsTab': 'Domains',
    'networks.networksTab': 'Networks',
    'networks.addDomain': 'Add Domain',
    'networks.addNetwork': 'Add Network',
    'networks.domainRequired': 'Domain name is required',
    'networks.domainUpdated': 'Domain updated',
    'networks.domainAdded': 'Domain added',
    'networks.networkRequired': 'Network name and domain are required',
    'networks.networkUpdated': 'Network updated',
    'networks.networkAdded': 'Network added',
    'networks.domainDeleted': 'Domain deleted',
    'networks.networkDeleted': 'Network deleted',
    'networks.addNewDomain': 'Add New Domain',
    'networks.addNewNetwork': 'Add New Network',
    'networks.domainName': 'Domain Name',
    'networks.networkName': 'Network Name',
    'networks.domain': 'Domain',
    'networks.selectDomain': 'Select Domain',
    'networks.dnsServers': 'DNS Servers (comma separated)',
    'networks.networksCount': 'networks',
    'networks.serversCount': 'servers',
    'networks.addDomainFirst': 'Add a domain to get started',
    'networks.addDomainThenNetwork': 'Add a domain first, then add networks',
    'networks.addNetworkToStart': 'Add a network to get started',

    // Common additions
    'common.descriptionLabel': 'Description',
    'common.notSpecified': 'Not specified',
    'common.example': 'Example',

    // Auth
    'auth.rememberMe': 'Remember Me',
    'auth.sessionExpired': 'Session Expired',
    'auth.pleaseLoginAgain': 'Please login again',
    'auth.login': 'Login',
    'auth.loggingIn': 'Logging in...',
    'auth.loginSuccess': 'Login successful',
    'auth.invalidCredentials': 'Invalid login credentials',

    // Server Enhancements
    'servers.beneficiary': 'Beneficiary/Department',
    'servers.primaryApp': 'Primary Application',
    'servers.businessOwner': 'Business Owner',
    'servers.veeamBackup': 'Veeam Backup',
    'servers.isBackedUp': 'Is Backed Up?',
    'servers.backupFrequency': 'Backup Frequency',
    'servers.backupJobName': 'Job Name',
    'servers.lastBackupStatus': 'Last Status',
    'servers.lastBackupDate': 'Last Backup Date',
    'servers.backupNone': 'None',
    'servers.backupDaily': 'Daily',
    'servers.backupWeekly': 'Weekly',
    'servers.filterByBackup': 'Backup Filter',
    'servers.filterByDepartment': 'Department Filter',
    'servers.backedUp': 'Backed Up',
    'servers.notBackedUp': 'Not Backed Up',

    // Network Scan
    'scan.title': 'Network Scan',
    'scan.startScan': 'Start Scan',
    'scan.scanName': 'Scan Name',
    'scan.ipRange': 'IP Range',
    'scan.scanMode': 'Scan Mode',
    'scan.basic': 'Basic',
    'scan.credentialed': 'Credentialed',
    'scan.results': 'Results',
    'scan.importSelected': 'Import Selected',
    'scan.discovered': 'Discovered',
    'scan.devices': 'devices',
    'scan.running': 'Running',
    'scan.completed': 'Completed',
    'scan.failed': 'Failed',
    'scan.pending': 'Pending',
    'scan.selectForImport': 'Select for Import',
    'scan.hostname': 'Hostname',
    'scan.deviceType': 'Device Type',
    'scan.openPorts': 'Open Ports',
    'scan.server': 'Server',
    'scan.workstation': 'Workstation',
    'scan.networkDevice': 'Network Device',
    'scan.printer': 'Printer',
    'scan.unknown': 'Unknown',
    'scan.history': 'Scan History',

    // Task System Pro
    'tasks.myTasks': 'My Tasks',
    'tasks.teamTasks': 'Team Tasks',
    'tasks.kanban': 'Kanban Board',
    'tasks.calendar': 'Calendar',
    'tasks.templates': 'Templates',
    'tasks.sla': 'SLA',
    'tasks.checklist': 'Checklist',
    'tasks.comments': 'Comments',
    'tasks.attachments': 'Attachments',
    'tasks.evidence': 'Evidence',
    'tasks.draft': 'Draft',
    'tasks.assigned': 'Assigned',
    'tasks.inProgress': 'In Progress',
    'tasks.blocked': 'Blocked',
    'tasks.inReview': 'In Review',
    'tasks.done': 'Done',
    'tasks.closed': 'Closed',
    'tasks.cancelled': 'Cancelled',
    'tasks.requester': 'Requester',
    'tasks.reviewer': 'Reviewer',
    'tasks.watchers': 'Watchers',
    'tasks.linkedAssets': 'Linked Assets',
    'tasks.subtasks': 'Subtasks',
    'tasks.addComment': 'Add Comment',
    'tasks.addEvidence': 'Add Evidence',
    'tasks.slaBreach': 'SLA Breach',
    'tasks.responseTime': 'Response Time',
    'tasks.resolveTime': 'Resolve Time',
    'tasks.overdueTasks': 'Overdue Tasks',
    'tasks.todayTasks': 'Today\'s Tasks',
    'tasks.upcomingTasks': 'Upcoming Tasks',

    // Priorities
    'priority.p1': 'Critical',
    'priority.p2': 'High',
    'priority.p3': 'Medium',
    'priority.p4': 'Low',
    
    // Additional Task Views
    'tasks.listView': 'List',
    'tasks.kanbanView': 'Kanban',
    'tasks.calendarView': 'Calendar',
    'tasks.viewModes': 'View Modes',
    'tasks.createFromTemplate': 'Create from Template',
    'tasks.manageTemplates': 'Manage Templates',
    'tasks.noTemplates': 'No templates',
    
    // Import/Export
    'import.review': 'Import Review',
    'import.newRecords': 'New Records',
    'import.toUpdate': 'To Update',
    'import.errors': 'Errors',
    'import.confirmImport': 'Confirm Import',
    'import.dryRun': 'Preview Only',
    'import.downloadTemplate': 'Download Template',
    
    'export.pdf': 'Export PDF',
    'export.excel': 'Export Excel',
    'export.fullReport': 'Full Report',
    'export.filtered': 'Filtered Data',
    'export.summary': 'Executive Summary',
    
    // Reports Networks
    'reports.networks': 'Networks',
    
    // Server Filters
    'servers.selectDomain': 'Select Domain',
    'servers.selectNetwork': 'Select Network',
    'servers.filterByDomain': 'Filter by Domain',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('it-manager-language');
    return (saved as Language) || 'ar';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('it-manager-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
