import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Extend jsPDF type to include autoTable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
    lastAutoTable: { finalY: number };
  }
}

// Brand Colors
const BRAND_TEAL = [11, 107, 99] as const; // #0B6B63
const BRAND_GOLD = [212, 175, 55] as const; // #D4AF37
const BRAND_LIGHT = [245, 245, 245] as const;

interface VacationExportData {
  employeeName: string;
  employeePosition: string;
  vacationType: string;
  startDate: string;
  endDate: string;
  daysCount: number;
  status: string;
  notes: string;
}

interface VacationSummary {
  totalDays: number;
  annualDays: number;
  sickDays: number;
  emergencyDays: number;
  unpaidDays: number;
  approvedCount: number;
  pendingCount: number;
  rejectedCount: number;
}

// ===================== BRANDED HEADER/FOOTER =====================

const addBrandedHeader = (doc: jsPDF, title: string) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Teal header bar
  doc.setFillColor(BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]);
  doc.rect(0, 0, pageWidth, 18, 'F');
  
  // Gold accent line
  doc.setFillColor(BRAND_GOLD[0], BRAND_GOLD[1], BRAND_GOLD[2]);
  doc.rect(0, 18, pageWidth, 2, 'F');
  
  // Company name in header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text('IT Infrastructure Manager', 10, 12);
  
  // Title
  doc.setFontSize(18);
  doc.setTextColor(BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]);
  doc.text(title, pageWidth / 2, 32, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  const dateStr = new Date().toLocaleDateString('ar-SA');
  doc.text(dateStr, pageWidth / 2, 40, { align: 'center' });
};

const addBrandedFooter = (doc: jsPDF, pageNumber: number, totalPages: number) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Footer line
  doc.setDrawColor(BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]);
  doc.setLineWidth(0.5);
  doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);
  
  // Page number
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(`${pageNumber} / ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
  
  // Generated by text
  doc.text('IT Infrastructure Management System', 15, pageHeight - 8);
};

// Get status color for cells
const getStatusColor = (status: string): [number, number, number] => {
  switch (status.toLowerCase()) {
    case 'completed':
    case 'done':
    case 'approved':
    case 'active':
      return [46, 125, 50]; // Green
    case 'pending':
    case 'in_progress':
    case 'in_review':
      return [255, 152, 0]; // Orange
    case 'overdue':
    case 'breached':
    case 'rejected':
    case 'inactive':
      return [198, 40, 40]; // Red
    default:
      return [100, 100, 100]; // Gray
  }
};

export const calculateVacationSummary = (vacations: any[]): VacationSummary => {
  return {
    totalDays: vacations.reduce((sum, v) => sum + (v.days_count || 0), 0),
    annualDays: vacations.filter(v => v.vacation_type === 'annual').reduce((sum, v) => sum + (v.days_count || 0), 0),
    sickDays: vacations.filter(v => v.vacation_type === 'sick').reduce((sum, v) => sum + (v.days_count || 0), 0),
    emergencyDays: vacations.filter(v => v.vacation_type === 'emergency').reduce((sum, v) => sum + (v.days_count || 0), 0),
    unpaidDays: vacations.filter(v => v.vacation_type === 'unpaid').reduce((sum, v) => sum + (v.days_count || 0), 0),
    approvedCount: vacations.filter(v => v.status === 'approved').length,
    pendingCount: vacations.filter(v => v.status === 'pending').length,
    rejectedCount: vacations.filter(v => v.status === 'rejected').length,
  };
};

export const exportVacationsPDF = (
  vacations: VacationExportData[],
  employeeName: string,
  summary: VacationSummary,
  isArabic: boolean = true
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  doc.setFont('helvetica');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  // Branded header
  addBrandedHeader(doc, isArabic ? 'تقرير الإجازات' : 'Vacation Report');

  // Employee Name
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  const employeeLabel = isArabic ? `الموظف: ${employeeName}` : `Employee: ${employeeName}`;
  doc.text(employeeLabel, pageWidth / 2, 50, { align: 'center' });

  // Summary Box with brand colors
  doc.setFillColor(BRAND_LIGHT[0], BRAND_LIGHT[1], BRAND_LIGHT[2]);
  doc.roundedRect(margin, 55, pageWidth - margin * 2, 35, 3, 3, 'F');
  
  // Gold border on left
  doc.setFillColor(BRAND_GOLD[0], BRAND_GOLD[1], BRAND_GOLD[2]);
  doc.rect(margin, 55, 3, 35, 'F');

  doc.setFontSize(12);
  doc.setTextColor(BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]);
  const summaryTitle = isArabic ? 'ملخص الإجازات' : 'Vacation Summary';
  doc.text(summaryTitle, margin + 8, 63);

  doc.setFontSize(10);
  const summaryItems = [
    { label: isArabic ? 'إجمالي الأيام:' : 'Total Days:', value: summary.totalDays },
    { label: isArabic ? 'سنوية:' : 'Annual:', value: summary.annualDays },
    { label: isArabic ? 'مرضية:' : 'Sick:', value: summary.sickDays },
    { label: isArabic ? 'طارئة:' : 'Emergency:', value: summary.emergencyDays },
    { label: isArabic ? 'بدون راتب:' : 'Unpaid:', value: summary.unpaidDays },
  ];

  let xPos = margin + 8;
  summaryItems.forEach((item) => {
    doc.setTextColor(100, 100, 100);
    doc.text(item.label, xPos, 73);
    doc.setTextColor(0, 0, 0);
    doc.text(String(item.value), xPos + doc.getTextWidth(item.label) + 2, 73);
    xPos += 35;
  });

  // Status summary with colored values
  const statusItems = [
    { label: isArabic ? 'موافق عليها:' : 'Approved:', value: summary.approvedCount, color: [46, 125, 50] },
    { label: isArabic ? 'معلقة:' : 'Pending:', value: summary.pendingCount, color: [255, 152, 0] },
    { label: isArabic ? 'مرفوضة:' : 'Rejected:', value: summary.rejectedCount, color: [198, 40, 40] },
  ];

  xPos = margin + 8;
  statusItems.forEach((item) => {
    doc.setTextColor(100, 100, 100);
    doc.text(item.label, xPos, 83);
    doc.setTextColor(item.color[0], item.color[1], item.color[2]);
    doc.text(String(item.value), xPos + doc.getTextWidth(item.label) + 2, 83);
    xPos += 45;
  });

  // Vacations Table with branded header
  const tableHeaders = isArabic 
    ? [['النوع', 'تاريخ البداية', 'تاريخ النهاية', 'الأيام', 'الحالة', 'ملاحظات']]
    : [['Type', 'Start Date', 'End Date', 'Days', 'Status', 'Notes']];

  const tableData = vacations.map((v) => [
    v.vacationType,
    v.startDate,
    v.endDate,
    String(v.daysCount),
    v.status,
    v.notes.substring(0, 30) + (v.notes.length > 30 ? '...' : ''),
  ]);

  doc.autoTable({
    head: tableHeaders,
    body: tableData,
    startY: 95,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      halign: isArabic ? 'right' : 'left',
    },
    headStyles: {
      fillColor: [BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [BRAND_LIGHT[0], BRAND_LIGHT[1], BRAND_LIGHT[2]],
    },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 28 },
      2: { cellWidth: 28 },
      3: { cellWidth: 15 },
      4: { cellWidth: 22 },
      5: { cellWidth: 'auto' },
    },
    didParseCell: (data: any) => {
      // Color status column
      if (data.column.index === 4 && data.section === 'body') {
        const color = getStatusColor(data.cell.raw);
        data.cell.styles.textColor = color;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // Footer
  const totalPages = (doc as any).internal.getNumberOfPages?.() || 1;
  addBrandedFooter(doc, 1, totalPages);

  // Save
  const filename = `vacations-${employeeName.replace(/\s+/g, '-')}-${Date.now()}.pdf`;
  doc.save(filename);
};

// ===================== GENERIC PDF EXPORT =====================

interface GenericPDFOptions {
  title: string;
  headers: string[];
  rows: string[][];
  filename?: string;
  isArabic?: boolean;
  statusColumnIndex?: number;
}

export const exportToPDF = (options: GenericPDFOptions) => {
  const { title, headers, rows, filename, isArabic = true, statusColumnIndex } = options;
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  doc.setFont('helvetica');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;

  // Branded header
  addBrandedHeader(doc, title);

  // Stats box
  doc.setFillColor(BRAND_LIGHT[0], BRAND_LIGHT[1], BRAND_LIGHT[2]);
  doc.roundedRect(margin, 45, pageWidth - margin * 2, 12, 2, 2, 'F');
  
  doc.setFontSize(11);
  doc.setTextColor(BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]);
  const statsText = isArabic ? `عدد السجلات: ${rows.length}` : `Total Records: ${rows.length}`;
  doc.text(statsText, margin + 5, 53);

  // Table with branded styling
  doc.autoTable({
    head: [headers],
    body: rows,
    startY: 62,
    margin: { left: margin, right: margin },
    styles: {
      fontSize: 9,
      cellPadding: 3,
      halign: isArabic ? 'right' : 'left',
    },
    headStyles: {
      fillColor: [BRAND_TEAL[0], BRAND_TEAL[1], BRAND_TEAL[2]],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [BRAND_LIGHT[0], BRAND_LIGHT[1], BRAND_LIGHT[2]],
    },
    didParseCell: (data: any) => {
      // Color status column if specified
      if (statusColumnIndex !== undefined && data.column.index === statusColumnIndex && data.section === 'body') {
        const color = getStatusColor(data.cell.raw);
        data.cell.styles.textColor = color;
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // Footer
  const totalPages = (doc as any).internal.getNumberOfPages?.() || 1;
  addBrandedFooter(doc, 1, totalPages);

  // Save
  const outputFilename = filename || `report-${Date.now()}.pdf`;
  doc.save(outputFilename);
};

// ===================== SERVERS PDF EXPORT =====================

interface ServerExportData {
  name: string;
  ip: string;
  os: string;
  environment: string;
  status: string;
  network: string;
  owner: string;
  veeamStatus: string;
}

export const exportServersPDF = (
  servers: ServerExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['اسم السيرفر', 'IP', 'نظام التشغيل', 'البيئة', 'الحالة', 'الشبكة', 'المسؤول', 'Veeam']
    : ['Server Name', 'IP', 'OS', 'Environment', 'Status', 'Network', 'Owner', 'Veeam'];
  
  const rows = servers.map(s => [
    s.name,
    s.ip,
    s.os,
    s.environment,
    s.status,
    s.network,
    s.owner,
    s.veeamStatus,
  ]);

  exportToPDF({
    title: isArabic ? 'تقرير السيرفرات' : 'Servers Report',
    headers,
    rows,
    filename: `servers-report-${Date.now()}.pdf`,
    isArabic,
    statusColumnIndex: 4,
  });
};

// ===================== TASKS PDF EXPORT =====================

interface TaskExportData {
  title: string;
  assignee: string;
  department: string;
  priority: string;
  status: string;
  dueDate: string;
}

export const exportTasksPDF = (
  tasks: TaskExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['المهمة', 'المسؤول', 'القسم', 'الأولوية', 'الحالة', 'تاريخ الاستحقاق']
    : ['Task', 'Assignee', 'Department', 'Priority', 'Status', 'Due Date'];
  
  const rows = tasks.map(t => [
    t.title,
    t.assignee,
    t.department,
    t.priority,
    t.status,
    t.dueDate,
  ]);

  exportToPDF({
    title: isArabic ? 'تقرير المهام' : 'Tasks Report',
    headers,
    rows,
    filename: `tasks-report-${Date.now()}.pdf`,
    isArabic,
    statusColumnIndex: 4,
  });
};

// ===================== LICENSES PDF EXPORT =====================

interface LicenseExportData {
  name: string;
  vendor: string;
  quantity: number;
  expiryDate: string;
  status: string;
  assignedTo: string;
}

export const exportLicensesPDF = (
  licenses: LicenseExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['اسم الترخيص', 'المورد', 'الكمية', 'تاريخ الانتهاء', 'الحالة', 'مخصص لـ']
    : ['License Name', 'Vendor', 'Quantity', 'Expiry Date', 'Status', 'Assigned To'];
  
  const rows = licenses.map(l => [
    l.name,
    l.vendor,
    String(l.quantity),
    l.expiryDate,
    l.status,
    l.assignedTo,
  ]);

  exportToPDF({
    title: isArabic ? 'تقرير التراخيص' : 'Licenses Report',
    headers,
    rows,
    filename: `licenses-report-${Date.now()}.pdf`,
    isArabic,
    statusColumnIndex: 4,
  });
};

// ===================== EMPLOYEES PDF EXPORT =====================

interface EmployeeExportData {
  name: string;
  email: string;
  department: string;
  position: string;
  role: string;
}

export const exportEmployeesPDF = (
  employees: EmployeeExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['الاسم', 'البريد الإلكتروني', 'القسم', 'المنصب', 'الدور']
    : ['Name', 'Email', 'Department', 'Position', 'Role'];
  
  const rows = employees.map(e => [
    e.name,
    e.email,
    e.department,
    e.position,
    e.role,
  ]);

  exportToPDF({
    title: isArabic ? 'تقرير الموظفين' : 'Employees Report',
    headers,
    rows,
    filename: `employees-report-${Date.now()}.pdf`,
    isArabic,
  });
};

// ===================== AUDIT LOG PDF EXPORT =====================

interface AuditLogExportData {
  timestamp: string;
  user: string;
  action: string;
  entity: string;
  details: string;
}

export const exportAuditLogPDF = (
  logs: AuditLogExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['التاريخ', 'المستخدم', 'الإجراء', 'الكيان', 'التفاصيل']
    : ['Date', 'User', 'Action', 'Entity', 'Details'];
  
  const rows = logs.map(l => [
    l.timestamp,
    l.user,
    l.action,
    l.entity,
    l.details.substring(0, 50) + (l.details.length > 50 ? '...' : ''),
  ]);

  exportToPDF({
    title: isArabic ? 'سجل التدقيق' : 'Audit Log',
    headers,
    rows,
    filename: `audit-log-${Date.now()}.pdf`,
    isArabic,
    statusColumnIndex: 2,
  });
};

// ===================== NETWORKS PDF EXPORT =====================

interface NetworkExportData {
  name: string;
  domain: string;
  subnet: string;
  gateway: string;
  dnsServers: string;
  serverCount: number;
}

export const exportNetworksPDF = (
  networks: NetworkExportData[],
  isArabic: boolean = true
) => {
  const headers = isArabic 
    ? ['الشبكة', 'النطاق', 'Subnet', 'Gateway', 'DNS', 'عدد السيرفرات']
    : ['Network', 'Domain', 'Subnet', 'Gateway', 'DNS', 'Server Count'];
  
  const rows = networks.map(n => [
    n.name,
    n.domain,
    n.subnet,
    n.gateway,
    n.dnsServers,
    String(n.serverCount),
  ]);

  exportToPDF({
    title: isArabic ? 'تقرير الشبكات' : 'Networks Report',
    headers,
    rows,
    filename: `networks-report-${Date.now()}.pdf`,
    isArabic,
  });
};
